### PR TITLE
Issue/Hero Image

### LINKED ISSUE #34: Home page/Hero image
### Description
To keep it simple and to enable users to take action quickly, we've decided that the browse page will be our home page

### User Story
As prospective student, when I arrive on this website, I understand what it's about and what I need to do next to make the best of it

### Resources

Image
Image

### Definition of Done
[Definition of Done](https://github.com/coforma/swift-tech-challenge/blob/main/documentation/product/definition_of_done.md)

### PR DESCRIPTION
**Pull request by ntsummers1**
# Title
Issue/Hero Image

# Summary
This PR adds a hero image to the top of the browse page

Fixes #34

## Desktop

Screenshot 2024-03-14 at 10 36 58 AM

## Mobile

Screenshot 2024-03-14 at 10 41 19 AM

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How To Test

1. run `yarn dev`, then navigate to `localhost:3000`
2. See the new mock hero image in action!

# Checklist:
- [x] My code follows the style guidelines of this project and has no linting errors
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have made corresponding changes to the documentation, including any applicable ADRs~
- [x] My changes generate no new warnings
- [x] I have added tests that fail without these changes~
- [x] New and existing tests (unit, integration, accessibility) pass locally~
- ~[ ] Documentation updated~
- ~[ ] If there are security concerns they are addressed or ticketed after being discussed~

### CODE REVIEW

**Review by gmrabian — DISMISSED** [review]
image and resizing look good

**Review by TheDanMiller — CHANGES_REQUESTED** [review]
Can you get with @skylerschain in the am and show him this live. There might be some quick tweaks we can incorporate to add some polish.

There is nothing technically wrong with it. Just do a typical over the shoulder so he can see it live

**Comment by ntsummers1** [comment]
> Can you get with @skylerschain in the am and show him this live. There might be some quick tweaks we can incorporate to add some polish.
> 
> There is nothing technically wrong with it. Just do a typical over the shoulder so he can see it live

Met with Skyler this morning. We made some changes to the look of the page its looking better!

**Review by gmrabian — APPROVED** [review]
pretty sweet

**Review by TheDanMiller — APPROVED** [review]

**Pull request merged**
